# 2. Ridge Regression

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import Ridge
# Ridge모델은 linear_model에서 Ridge로 불러올 수 있습니다.

In [2]:
X_multi, y_multi = make_regression(n_samples = 1000, n_features = 30, bias = 10, noise = 50)
X_train, X_test, y_train, y_test = train_test_split(X_multi, y_multi, test_size = 0.3, shuffle = True)

In [3]:
model_Ridge = Ridge().fit(X_train, y_train)

In [4]:
print('weight : \n{}\n\n'.format(model_Ridge.coef_))
print('bias : \n{}'.format(model_Ridge.intercept_))

weight : 
[-0.3286743  -1.5909729  72.75771321 96.33289302 -1.13432957 -0.38757351
  0.38748983  0.29877077 25.45180216 -0.4212048  93.87171259 -0.66250894
 92.96272496 76.84180306 -1.20606968 -2.84874871 -4.35845813 -2.09598579
 -0.56720122 51.87375834  4.1062455   0.78893144 -1.30852622 90.94491111
 -1.08521472 21.51728976  0.79199108 64.93141106  1.03704897 -1.25265678]


bias : 
10.975235796405508


In [5]:
from sklearn.linear_model import LinearRegression
model_Linear = LinearRegression().fit(X_train, y_train)
model_Linear.coef_

array([-0.32759033, -1.57802669, 72.86162022, 96.47263128, -1.14840109,
       -0.37228499,  0.37063089,  0.31190637, 25.49515577, -0.40455644,
       94.03213742, -0.64730849, 93.12333315, 76.95188651, -1.21889994,
       -2.86101838, -4.37062463, -2.08814798, -0.54201247, 51.95122766,
        4.11292495,  0.78138408, -1.31167141, 91.09165745, -1.08857602,
       21.5497277 ,  0.80610018, 65.04176009,  1.03514642, -1.25485083])

weight를 살펴보면 0에 가깝게 변한 값들을 볼 수 있다.

In [6]:
print('train score : {:.2f}'.format(model_Ridge.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_Ridge.score(X_test, y_test)))

train score : 0.96
test score : 0.95


Ridge는 alpha라는 파라미터를 가지고 있다. 기본값은 1.0  
최적의 alpha값은 정해진 것이 없고 데이터셋마다 다르다.

In [7]:
model_ridge500 = Ridge(alpha =500).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ridge500.coef_))
print('bias : \n{}'.format(model_ridge500.intercept_))

weight : 
[-0.52703452 -3.54540244 42.76124355 56.18803415  1.3649401  -2.75314554
  2.5776876  -1.76756446 14.10294638 -2.9263499  50.75419404 -2.77058368
 50.30213103 44.82140568  0.85158558 -0.29661141 -1.65242588 -2.9655759
 -4.52708009 29.71474043  2.2798134   1.68456594 -0.7199902  50.70162002
 -0.55383986 12.53983544 -1.60054629 35.29663293  1.26512507 -0.57588087]


bias : 
15.086861070313496


In [8]:
print('train score : {:.2f}'.format(model_ridge500.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_ridge500.score(X_test, y_test)))

train score : 0.78
test score : 0.77


alpha값을 높이면 0에 가깝게 만들어 훈련 셋의 성능은 나빠지지만 일반화에 도움을 준다.

In [9]:
model_ridge005 = Ridge(alpha = 0.005).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ridge005.coef_))
print('bias : \n{}'.format(model_ridge005.intercept_))

weight : 
[-0.32759576 -1.57809162 72.86109992 96.47193155 -1.14833053 -0.37236167
  0.3707155   0.31184048 25.49493859 -0.40463994 94.03133392 -0.64738476
 93.12252869 76.95133532 -1.21883558 -2.86095689 -4.37056365 -2.08818732
 -0.54213881 51.95083974  4.1128915   0.78142197 -1.31165563 91.09092251
 -1.08855915 21.54956524  0.80602942 65.0412074   1.03515596 -1.25483985]


bias : 
10.959637093718415


In [10]:
print('train score : {:.2f}'.format(model_ridge005.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_ridge005.score(X_test, y_test)))

train score : 0.96
test score : 0.95


반대로 alpha값을 낮추게 되면 제한을 하지 않으므로 선형회귀와 비슷해진다.

In [11]:
# 선형회귀와 비교
from sklearn.linear_model import LinearRegression
hypothesis_multi = LinearRegression()
model_linear_multi = hypothesis_multi.fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_linear_multi.coef_))
print('bias : \n{}'.format(model_linear_multi.intercept_))

weight : 
[-0.32759033 -1.57802669 72.86162022 96.47263128 -1.14840109 -0.37228499
  0.37063089  0.31190637 25.49515577 -0.40455644 94.03213742 -0.64730849
 93.12333315 76.95188651 -1.21889994 -2.86101838 -4.37062463 -2.08814798
 -0.54201247 51.95122766  4.11292495  0.78138408 -1.31167141 91.09165745
 -1.08857602 21.5497277   0.80610018 65.04176009  1.03514642 -1.25485083]


bias : 
10.959558564130619


In [12]:
print('학습 데이터 점수 : {:.2f}'.format(model_linear_multi.score(X_train, y_train)))
print('검증 데이터 점수 : {:.2f}'.format(model_linear_multi.score(X_test, y_test)))

학습 데이터 점수 : 0.96
검증 데이터 점수 : 0.95


# 3. Lasso Regression

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import Lasso
import numpy as np
# Lasso모델은 linear_model에서 Lasso로 불러올 수 있습니다.

In [14]:
model_lasso = Lasso(alpha=10).fit(X_train, y_train)

In [15]:
print('weight : \n{}\n\n'.format(model_lasso.coef_))
print('bias : \n{}'.format(model_lasso.intercept_))

weight : 
[-0.         -0.         63.35837004 87.20960966  0.         -0.
  0.         -0.         14.96254999 -0.         81.33246199 -0.
 82.49788278 66.82544071  0.         -0.         -0.         -0.
 -0.         41.25038347  0.          0.         -0.         79.68998545
 -0.         10.9068548  -0.         53.23054603  0.         -0.        ]


bias : 
11.4203401722948


Lasso의 weight를 살펴보면 Ridge와는 다르게 0으로 가까워지다 못해 0이 되어버린 값들을 살펴볼 수 있다.  
lasso에서 alpha의 기본값은 1.0으로 설정되어있다.

In [16]:
print('사용된 특성 수 : {}개'.format(np.sum(model_lasso.coef_ != 0)))
# 100개의 특성중 몇개의 특성을 사용했는지 확인해볼 수 있다.

사용된 특성 수 : 10개


In [17]:
print('train score : {:.2f}'.format(model_ridge005.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_ridge005.score(X_test, y_test)))

train score : 0.96
test score : 0.95


In [18]:
model_lasso005 = Lasso(alpha = 0.05, max_iter = 100000).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_lasso005.coef_))
print('bias : \n{}'.format(model_lasso005.intercept_))

weight : 
[-0.30674865 -1.53323924 72.81505965 96.41786827 -1.08588379 -0.32424737
  0.322351    0.23595156 25.42907117 -0.34845004 93.97583866 -0.59846147
 93.07288406 76.90623399 -1.15795091 -2.81617449 -4.31662696 -2.04619883
 -0.51111045 51.90533839  4.05839814  0.72672084 -1.25589119 91.0424146
 -1.05321115 21.49451332  0.72950773 64.98377332  0.97847915 -1.20775051]


bias : 
10.955460147328944


- alpha를 줄이게 되면 가장 낮은 오차를 찾아가는 반복횟수가 늘어야 한다. 그러므로 max_iter라는 파라미터를 증가시켜주면 된다.

In [19]:
print('train score : {:.2f}'.format(model_lasso005.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_lasso005.score(X_test, y_test)))

train score : 0.96
test score : 0.95


In [20]:
print('사용된 특성 수 : {}개'.format(np.sum(model_lasso005.coef_ != 0)))

사용된 특성 수 : 30개


In [21]:
model_lasso50 = Lasso(alpha = 50, max_iter = 1000).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_lasso50.coef_))
print('bias : \n{}'.format(model_lasso50.intercept_))

weight : 
[-0.         -0.         23.97314976 48.89098623  0.         -0.
  0.         -0.          0.         -0.         32.43634082 -0.
 38.10704079 26.04441457  0.          0.          0.         -0.
 -0.          0.          0.          0.         -0.         34.24716211
 -0.          0.         -0.          7.60309599  0.         -0.        ]


bias : 
14.936680701300109


In [22]:
print('사용된 특성 수 : {}개'.format(np.sum(model_lasso50.coef_ != 0)))

사용된 특성 수 : 7개


In [23]:
print('train score : {:.2f}'.format(model_lasso50.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_lasso50.score(X_test, y_test)))

train score : 0.53
test score : 0.53


- train, test 둘 다 점수가 좋지 않은것을 확인할 수 있다. underfiting되었다고 볼 수 있다.

# 4. Elastic Net

- Elastic Net은 Ridge와 Lasso를 절충한 모델이다.

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression
from sklearn.linear_model import ElasticNet

In [25]:
model_ela = ElasticNet().fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : \n{}'.format(model_ela.intercept_))

weight : 
[-0.22184191 -3.13076871 48.49078973 63.87738301  0.7694944  -2.3113093
  2.18866692 -1.30411304 15.9408222  -2.43132614 58.50754622 -2.33788887
 58.01245541 50.9027251   0.29354836 -0.32012405 -1.74048828 -2.74245214
 -4.00584935 33.73953758  2.28265249  1.31521339 -0.53072083 58.12324065
 -0.33783549 13.97438977 -1.06037933 40.53346632  0.93051789 -0.38710338]


bias : 
14.300102922698148


In [26]:
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

사용된 특성 수 : 30개


In [27]:
print('train score : {:.2f}'.format(model_ela.score(X_train, y_train)))
print('test score : {:.2f}'.format(model_ela.score(X_test, y_test)))

train score : 0.84
test score : 0.83


In [28]:
model_ela = ElasticNet(alpha = 0.1, l1_ratio = 0.1).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : {}\n\n'.format(model_ela.intercept_))
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

weight : 
[-3.80904616e-01 -2.24825598e+00  6.68563989e+01  8.84021589e+01
 -3.89279174e-01 -1.16314400e+00  1.21283318e+00 -3.66712913e-01
  2.30376465e+01 -1.26209284e+00  8.48853378e+01 -1.41766748e+00
  8.39991893e+01  7.05695435e+01 -5.41491379e-01 -2.18463697e+00
 -3.69278787e+00 -2.47662601e+00 -1.85543130e+00  4.74725122e+01
  3.72237912e+00  1.15025426e+00 -1.13775020e+00  8.26975226e+01
 -9.11591714e-01  1.96868789e+01  4.69631912e-02  5.87499005e+01
  1.12368103e+00 -1.11553622e+00]


bias : 11.845888207944412


사용된 특성 수 : 30개


- alpha = l1(lasso) + l2(ridge)  
- l1_ratio = 0 이면 ridge 1 이면 lasso, lasso의 비율을 정해준다.

In [ ]:
model_ela = ElasticNet(alpha = 0.1, l1_ratio = 0.9).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : {}\n\n'.format(model_ela.intercept_))
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

weight : 
[-0.89703736  0.         61.28708701 20.32865079 64.26765996 -0.85732805
 -1.66108169 98.63945321  0.90831094 79.60343576 74.79543719 -2.67909343
  8.37919032 -1.84598229  2.46547991 -1.75509326 79.51624575 -3.4530337
 -0.35743888 -1.45529918  1.39664796  0.99831797  0.32377662 44.26211191
  0.16466486  1.85333855 36.96004024 -0.30530688  0.         -1.20060565]


bias : 13.74240201566646


사용된 특성 수 : 28개


In [ ]:
model_ela = ElasticNet(alpha = 1, l1_ratio = 0.1).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : {}\n\n'.format(model_ela.intercept_))
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

weight : 
[-7.47154255e-01 -4.25852915e-01  3.57573133e+01  9.43902393e+00
  3.06574358e+01  2.01724894e+00 -3.84465076e-01  5.03403363e+01
  2.18615201e+00  4.40335682e+01  3.86720514e+01  2.81343027e-01
  4.65843708e+00 -2.11056913e-02  3.56562047e-01  2.68040800e-01
  4.07217713e+01 -2.89906078e+00 -3.94697121e-01 -2.48086132e+00
  3.07418200e+00  1.69225159e+00  3.61951560e+00  2.30782725e+01
 -1.36812028e+00  2.74839622e+00  1.84469975e+01  1.76240772e+00
 -1.96034128e-01 -1.43439958e-01]


bias : 11.166217840220204


사용된 특성 수 : 30개


In [ ]:
model_ela = ElasticNet(alpha = 1, l1_ratio = 0.9).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : {}\n\n'.format(model_ela.intercept_))
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

weight : 
[-2.16594879e-02 -0.00000000e+00  5.64777727e+01  1.73991110e+01
  5.71612180e+01  0.00000000e+00 -5.15448726e-01  8.90149316e+01
  4.56488901e-01  7.28872599e+01  6.75678952e+01 -1.14159126e+00
  6.88938817e+00 -7.20417830e-01  1.20272985e+00 -3.97621839e-01
  7.17457183e+01 -2.73665636e+00 -0.00000000e+00 -1.01129191e+00
  1.38106333e+00  4.79154803e-01  5.90464084e-01  3.99220869e+01
 -0.00000000e+00  1.53690914e+00  3.27276033e+01  0.00000000e+00
 -0.00000000e+00 -2.52686654e-01]


bias : 13.158647151372325


사용된 특성 수 : 24개


In [ ]:
model_ela = ElasticNet(alpha = 10, l1_ratio = 0.1).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : {}\n\n'.format(model_ela.intercept_))
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

weight : 
[-1.13282994  0.3154853   0.          0.47440792  0.01144227  8.43199846
  6.73910978 -1.504788    5.73217631  0.48925841  0.2524967  -0.27441126
  0.90597591  1.04798865 -0.          2.08849122 -0.57549574  0.26308036
 -0.6271671   0.2175062   0.20407191  8.34287751  0.01567771  0.85312309
  0.76798061  0.49729112 -0.37757582  0.29449833 -1.29261439  0.8286318
  3.77534482  0.41302063 -0.45303207  0.25774945  0.          0.06353167
  0.11422131 -1.47128441  0.          1.05045839  0.80196647  0.
 -0.2107255   0.          0.87582937 -0.56928846 -0.09264119  0.52400331
 -1.212436    0.68608284 -0.09054618  0.8727593  -0.87350195  2.41513104
  0.24287545  0.20835476  0.11602144  4.2120822   0.79957203  0.
 -1.04120452 -0.92188092  0.20312081 -0.35729786  0.73208089  0.08545431
 -0.         -0.28923594 -0.7463571   0.7426032   8.11790525  0.42518815
  0.         -0.15252688 -1.14165362  0.49978392  0.35357063  0.
 -0.17906016  0.          0.53324026  0.12041719  0.          1.26

In [ ]:
model_ela = ElasticNet(alpha = 10, l1_ratio = 0.9).fit(X_train, y_train)
print('weight : \n{}\n\n'.format(model_ela.coef_))
print('bias : {}\n\n'.format(model_ela.intercept_))
print('사용된 특성 수 : {}개'.format(np.sum(model_ela.coef_ != 0)))

weight : 
[-0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  3.89854723e+01  3.18792386e+01 -3.04277898e-02
  2.65255693e+01  0.00000000e+00  0.00000000e+00 -0.00000000e+00
  0.00000000e+00  0.00000000e+00  0.00000000e+00  6.25529286e+00
 -0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
  0.00000000e+00  3.62203238e+01  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  1.58384067e+01  0.00000000e+00
 -0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00 -1.13866873e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00 -0.00000000e+00 -0.00000000e+00
  0.00000000e+00 -0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -3.27620506e-01  0.00000000e+00 -0.00000000e+00  0.00000000e+00
 -0.00000000e+00  8.91422369e+00  0.00000000e+00  0.00000000e+00
  0.00000000e+00  1.76300379e+01  0.00000000e+00  0.00000000e+00
 -0.00000000e+0

#### 보스턴 주택데이터 예측하기

In [179]:
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_boston

In [180]:
boston_data = load_boston()

In [181]:
X_data, y_data = boston_data['data'], boston_data['target']

In [182]:
model_linear = LinearRegression()
model_ridge = Ridge(alpha=0.5)
model_lasso = Lasso(alpha=0.5)
model_elastic = ElasticNet(alpha=0.5, l1_ratio=0.1)

In [183]:
model_linear.fit(X_data, y_data)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [184]:
model_ridge.fit(X_data, y_data) #alpha = 규제항의 파라미터

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [185]:
model_lasso.fit(X_data, y_data)

Lasso(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [186]:
model_elastic.fit(X_data, y_data)

ElasticNet(alpha=0.5, copy_X=True, fit_intercept=True, l1_ratio=0.1,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=None, selection='cyclic', tol=0.0001, warm_start=False)

In [188]:
model_linear.coef_, model_linear.intercept_
np.mean(np.square(model_linear.coef_))

26.21958706061755

In [189]:
model_ridge.coef_, model_ridge.intercept_
np.mean(np.square(model_ridge.coef_))

15.751041728901992

In [192]:
model_ridge.coef_

array([-1.05865684e-01,  4.70411564e-02,  2.25165173e-03,  2.61211652e+00,
       -1.34162609e+01,  3.84075720e+00, -3.14417004e-03, -1.41149067e+00,
        2.95989418e-01, -1.26863875e-02, -9.04760119e-01,  9.53768594e-03,
       -5.29832258e-01])

In [190]:
model_lasso.coef_, model_lasso.intercept_

(array([-0.0832894 ,  0.04954355, -0.0052532 ,  0.        , -0.        ,
         2.49821246,  0.00360438, -0.93660469,  0.27745115, -0.01544219,
        -0.75875211,  0.00946855, -0.6562895 ]), 32.520860962576535)

In [191]:
model_elastic.coef_, model_elastic.intercept_

(array([-0.09847129,  0.05541055, -0.04728805,  0.2457419 , -0.        ,
         1.49879517,  0.01174787, -1.00483821,  0.32691086, -0.01655082,
        -0.81813021,  0.00882847, -0.71886801]), 41.03790418751204)